<?php

/**
 * @file hosting_queued.module
 * Contains hooks for the queue daemon module.
 */

/**
 * Implements hook_menu().
 */
function hosting_queued_menu() {
  $items = [];
  $items['admin/hosting/queued'] = ['title' => 'Queue daemon', 'description' => 'Configure the daemonized tasks queue daemon.', 'page callback' => 'drupal_get_form', 'page arguments' => ['hosting_queued_settings_form'], 'access arguments' => ['administer hosting queues'], 'type' => MENU_LOCAL_TASK, 'file' => 'hosting_queued.admin.inc'];
  $items['admin/hosting/queued/semaphore'] = ['title' => 'Unlock Hosting Queue', 'description' => 'Remove the semaphore lock.', 'page callback' => 'drupal_get_form', 'page arguments' => ['hosting_queued_remove_semaphore_form'], 'access arguments' => ['administer hosting queues'], 'type' => MENU_LOCAL_TASK, 'file' => 'hosting_queued.admin.inc'];
  return $items;
}
